webpackJsonp([0,6],{

/***/ 493:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(11);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_pages_pages_module__ = __webpack_require__(154);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__(31);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_router__ = __webpack_require__(14);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__help_help_component_ngfactory__ = __webpack_require__(152);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__about_about_component_ngfactory__ = __webpack_require__(151);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__app_pages_help_help_component__ = __webpack_require__(62);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__app_pages_about_about_component__ = __webpack_require__(61);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "PagesModuleNgFactory", function() { return PagesModuleNgFactory; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();








var PagesModuleInjector = (function (_super) {
    __extends(PagesModuleInjector, _super);
    function PagesModuleInjector(parent) {
        return _super.call(this, parent, [
            __WEBPACK_IMPORTED_MODULE_4__help_help_component_ngfactory__["a" /* HelpComponentNgFactory */],
            __WEBPACK_IMPORTED_MODULE_5__about_about_component_ngfactory__["a" /* AboutComponentNgFactory */]
        ], []) || this;
    }
    Object.defineProperty(PagesModuleInjector.prototype, "_NgLocalization_3", {
        get: function () {
            if ((this.__NgLocalization_3 == null)) {
                (this.__NgLocalization_3 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["a" /* NgLocaleLocalization */](this.parent.get(__WEBPACK_IMPORTED_MODULE_0__angular_core__["c" /* LOCALE_ID */])));
            }
            return this.__NgLocalization_3;
        },
        enumerable: true,
        configurable: true
    });
    PagesModuleInjector.prototype.createInternal = function () {
        this._CommonModule_0 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */]();
        this._RouterModule_1 = new __WEBPACK_IMPORTED_MODULE_3__angular_router__["q" /* RouterModule */](this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["r" /* ɵa */], null), this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["j" /* Router */], null));
        this._PagesModule_2 = new __WEBPACK_IMPORTED_MODULE_1__app_pages_pages_module__["a" /* PagesModule */]();
        this._ROUTES_4 = [[
                {
                    path: 'help',
                    outlet: 'page',
                    component: __WEBPACK_IMPORTED_MODULE_6__app_pages_help_help_component__["a" /* HelpComponent */]
                },
                {
                    path: 'about',
                    outlet: 'page',
                    component: __WEBPACK_IMPORTED_MODULE_7__app_pages_about_about_component__["a" /* AboutComponent */]
                }
            ]
        ];
        return this._PagesModule_2;
    };
    PagesModuleInjector.prototype.getInternal = function (token, notFoundResult) {
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */])) {
            return this._CommonModule_0;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_router__["q" /* RouterModule */])) {
            return this._RouterModule_1;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_1__app_pages_pages_module__["a" /* PagesModule */])) {
            return this._PagesModule_2;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["g" /* NgLocalization */])) {
            return this._NgLocalization_3;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_router__["u" /* ROUTES */])) {
            return this._ROUTES_4;
        }
        return notFoundResult;
    };
    PagesModuleInjector.prototype.destroyInternal = function () {
    };
    return PagesModuleInjector;
}(__WEBPACK_IMPORTED_MODULE_0__angular_core__["B" /* ɵNgModuleInjector */]));
var PagesModuleNgFactory = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["C" /* NgModuleFactory */](PagesModuleInjector, __WEBPACK_IMPORTED_MODULE_1__app_pages_pages_module__["a" /* PagesModule */]);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L29wZW4tc291cmNlL2FuZ3VsYXItZ29vZ2xlLW1hcHMvc3JjL2FwcC8rcGFnZXMvcGFnZXMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0Rldi9vcGVuLXNvdXJjZS9hbmd1bGFyLWdvb2dsZS1tYXBzL3NyYy9hcHAvK3BhZ2VzL3BhZ2VzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
//# sourceMappingURL=pages.module.ngfactory.js.map

/***/ })

});
//# sourceMappingURL=0.chunk.js.map