webpackJsonp([1,6],{

/***/ 492:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(11);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_maps_maps_module__ = __webpack_require__(153);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__(31);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_router__ = __webpack_require__(14);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__app_maps_maps_service__ = __webpack_require__(92);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__app_maps_main_map_main_map_service__ = __webpack_require__(22);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__map_point_preview_map_point_preview_component_ngfactory__ = __webpack_require__(150);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__app_maps_map_point_preview_map_point_preview_component__ = __webpack_require__(60);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "MapsModuleNgFactory", function() { return MapsModuleNgFactory; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();








var MapsModuleInjector = (function (_super) {
    __extends(MapsModuleInjector, _super);
    function MapsModuleInjector(parent) {
        return _super.call(this, parent, [__WEBPACK_IMPORTED_MODULE_6__map_point_preview_map_point_preview_component_ngfactory__["a" /* MapPointPreviewComponentNgFactory */]], []) || this;
    }
    Object.defineProperty(MapsModuleInjector.prototype, "_NgLocalization_3", {
        get: function () {
            if ((this.__NgLocalization_3 == null)) {
                (this.__NgLocalization_3 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["a" /* NgLocaleLocalization */](this.parent.get(__WEBPACK_IMPORTED_MODULE_0__angular_core__["c" /* LOCALE_ID */])));
            }
            return this.__NgLocalization_3;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(MapsModuleInjector.prototype, "_MapsService_5", {
        get: function () {
            if ((this.__MapsService_5 == null)) {
                (this.__MapsService_5 = new __WEBPACK_IMPORTED_MODULE_4__app_maps_maps_service__["a" /* MapsService */]());
            }
            return this.__MapsService_5;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(MapsModuleInjector.prototype, "_MainMapService_6", {
        get: function () {
            if ((this.__MainMapService_6 == null)) {
                (this.__MainMapService_6 = new __WEBPACK_IMPORTED_MODULE_5__app_maps_main_map_main_map_service__["a" /* MainMapService */](this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["j" /* Router */]), this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["v" /* ActivatedRoute */])));
            }
            return this.__MainMapService_6;
        },
        enumerable: true,
        configurable: true
    });
    MapsModuleInjector.prototype.createInternal = function () {
        this._CommonModule_0 = new __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */]();
        this._RouterModule_1 = new __WEBPACK_IMPORTED_MODULE_3__angular_router__["q" /* RouterModule */](this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["r" /* ɵa */], null), this.parent.get(__WEBPACK_IMPORTED_MODULE_3__angular_router__["j" /* Router */], null));
        this._MapsModule_2 = new __WEBPACK_IMPORTED_MODULE_1__app_maps_maps_module__["a" /* MapsModule */]();
        this._ROUTES_4 = [[{
                    path: 'place/:pointId',
                    component: __WEBPACK_IMPORTED_MODULE_7__app_maps_map_point_preview_map_point_preview_component__["a" /* MapPointPreviewComponent */]
                }
            ]];
        return this._MapsModule_2;
    };
    MapsModuleInjector.prototype.getInternal = function (token, notFoundResult) {
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */])) {
            return this._CommonModule_0;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_router__["q" /* RouterModule */])) {
            return this._RouterModule_1;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_1__app_maps_maps_module__["a" /* MapsModule */])) {
            return this._MapsModule_2;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_2__angular_common__["g" /* NgLocalization */])) {
            return this._NgLocalization_3;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_3__angular_router__["u" /* ROUTES */])) {
            return this._ROUTES_4;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_4__app_maps_maps_service__["a" /* MapsService */])) {
            return this._MapsService_5;
        }
        if ((token === __WEBPACK_IMPORTED_MODULE_5__app_maps_main_map_main_map_service__["a" /* MainMapService */])) {
            return this._MainMapService_6;
        }
        return notFoundResult;
    };
    MapsModuleInjector.prototype.destroyInternal = function () {
    };
    return MapsModuleInjector;
}(__WEBPACK_IMPORTED_MODULE_0__angular_core__["B" /* ɵNgModuleInjector */]));
var MapsModuleNgFactory = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["C" /* NgModuleFactory */](MapsModuleInjector, __WEBPACK_IMPORTED_MODULE_1__app_maps_maps_module__["a" /* MapsModule */]);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L29wZW4tc291cmNlL2FuZ3VsYXItZ29vZ2xlLW1hcHMvc3JjL2FwcC8rbWFwcy9tYXBzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvb3Blbi1zb3VyY2UvYW5ndWxhci1nb29nbGUtbWFwcy9zcmMvYXBwLyttYXBzL21hcHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
//# sourceMappingURL=maps.module.ngfactory.js.map

/***/ })

});
//# sourceMappingURL=1.chunk.js.map